# Generated by Django 2.0.1 on 2018-01-30 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
